[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.148.1"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.148.1"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "development"
  HUGO_ENABLEGITINFO = "true"

[context.branch-deploy.environment]
  HUGO_VERSION = "0.148.1"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "development"
  HUGO_ENABLEGITINFO = "true"

[[headers]]
for = "/js/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

[[headers]]
for = "/css/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"

